source 'https://rubygems.org'

gem "github-pages"

# enable tzinfo-data for local build
# gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw]
gem 'jekyll-paginate'
gem 'webrick'

gem "erb", "~> 6.0"
