name: test and send code coverage to codecov.io
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: linux
      PYTHON: '3.6'
    steps:
    - name: checkout the repo 
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Run test and generate coverage report
      working-directory: ./mmif-python
      run: |
        pip install -r requirements.txt
        pip install -r requirements.dev
        echo "codecov.dev" > VERSION
        python setup.py sdist
        python -m pytest --doctest-modules --cov=mmif/ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./mmif-python/coverage.xml
        flags: unittests
        env_vars: OS,PYTHON
        name: coverage
        fail_ci_if_error: true
        path_to_write_report: ./mmif-python/codecov_report.gz
