name: upload HTML documentation, PyPI distribution

on: 
  push: 
    tags: '[0-9]+.[0-9]+.[0-9]+'
jobs:
  build-and-upload:
    name: documentation and pypi
    uses: clamsproject/.github/.github/workflows/sdk-publish.yml@main
